web/webapp/news/models.py
from webapp.db import db

class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return f'<News {self.title} {self.url}>'

web/webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db

class User(db.Model, UserMixin):
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50))

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def get_id(self):
        return self.user_id

    @property
    def is_admin(self):
        return self.role == "admin"

    def __repr__(self):
        return f'<User {self.username}>'

web/webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User

class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня!', default=True, render_kw={"class": "form-check-input"})
    submit = SubmitField('Отправить!', render_kw={"class": "btn btn-primary"})

class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired(),], render_kw={"class": "form-control"})
    email = StringField('Почта', validators=[DataRequired(), Email()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    password2 = PasswordField('Повторите пароль', validators=[DataRequired(), EqualTo('password')], render_kw={"class": "form-control"})
    submit = SubmitField('Отправить!', render_kw={"class": "btn btn-primary"})

    def validate_username(self, username):
        users_count = User.query.filter_by(username=username.data).count()
        if users_count > 0:
            raise ValidationError('Пользователь с таким именем уже зарегистрирован')

    def validate_email(self, email):
        users_count = User.query.filter_by(email=email.data).count()
        if users_coutn > 0:
            raise ValidationError('Пользователь с такой почтой уже зарегистрирован')

web/webapp/__init__.py
from flask import Flask, render_template, flash, redirect, url_for
from flask_login import LoginManager, current_user, login_required
from flask_migrate import Migrate

from webapp.db import db
from webapp.admin.views import blueprint as admin_blueprint
from webapp.news.views import blueprint as news_blueprint
from webapp.user.views import blueprint as user_blueprint
from webapp.user.models import User


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile("config.py")
    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = "user.login"
    
    app.register_blueprint(user_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app

web/webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required


blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route("/")
@admin_required
def admin_index():
    title = "Панель администратора"
    return render_template('admin/index.html', page_title=title)

web/webapp/news/views.py
from flask import Blueprint, render_template, current_app
from webapp.news.models import News
from webapp.weather import weather_by_city

blueprint = Blueprint('news', __name__)

@blueprint.route("/")
def index():
    title = "Новости Python"
    weather = weather_by_city(current_app.config["WEATHER_DEFAULT_CITY"])
    news_list = News.query.order_by(News.published.desc()).all()

    return render_template("news/index.html", page_title=title,
                            weather=weather, news_list=news_list)

web/webapp/user/views.py
from flask_login import login_user, logout_user, current_user, login_required
from flask import Blueprint, render_template, flash, redirect, url_for

from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp import db

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route("/login")
def login():
    print(current_user)
    if current_user.is_authenticated:
        return redirect(url_for("news.index"))
    title = "Авторизация"
    login_form = LoginForm()
    return render_template("user/login.html", page_title=title, form=login_form)

@blueprint.route("/process-login", methods=["POST"])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт!")
            return redirect(url_for("news.index"))

    flash("Неправильное имя или пароль!")
    return redirect(url_for("user.login"))

@blueprint.route("/logout")
def logout():
    logout_user()
    flash("Вы вышли из аккаунта")
    return redirect(url_for("news.index"))

@blueprint.route("/register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for("news.index"))
    title = "Регистрация"
    form = RegistrationForm()
    return render_template("user/registration.html", page_title=title, form=form)

@blueprint.route("/process-reg", methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле {getattr(form, field).label.text}: {error}')
        return redirect(url_for('user.register'))

web/webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include 'menu.html' %}
    <div class='container'>
        <h1>{{ page_title }}</h1>
        {% block content %}{% endblock %}
    </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    
  </body>
</html>

web/webapp/templates/index.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class='conteiner'>
    <h1>{{ page_title }}</h1>
    <div class="row">
        <div class='col-8'>
            <h2>Новости</h2>
            {% for news in news_list %}
            <h3><a href='{{ news.url }}'>{{ news.title }} </a></h3>
            <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
            <hr />
            {% endfor %}
        </div>
        <div class="col-4">
            <h2>Прогноз погоды</h2>
            {% if weather %}
                Погода: {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
            {% else %}
                Сервис погоды недоступен
            {% endif %}
        </div>
    </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    
  </body>
</html>

web/webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Новости Python</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Главная страница</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Искать</button>
      </form>
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link">Привет, {{ current_user.username }}!</span>
          </li>
          {% if current_user.is_admin %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

web/webapp/templates/news/index.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class='col-8'>
      {% with message = get_flashed_messages() %}
        {% if messages %}
        <div class="alert-warning" role="alert">
          {% for message in messages %}
            { message }<br>
          {% endfor %}
        </div>
        {% endif %}
      {% endwith %}
      <h2>Новости</h2>
      {% for news in news_list %}
        <h4><a href='{{ news.url }}'>{{ news.title }} </a></h4>
        <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
        <hr />
      {% endfor %}
    </div>
    <div class="col-4">
      <h2>Прогноз погоды</h2>
      {% if weather %}
        {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
      {% else %}
        Сервис погоды недоступен
      {% endif %}
    </div>
  </div>
{% endblock %}

web/webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class='col-4'>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-warning" role="alert">
          {% for message in messages %}
            {{ message }}<br>
          {% endfor %}
        </div>
        {% endif %}
      {% endwith %}
      <form action="{{ url_for('user.process_login') }}" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3">
          {{ form.username.label }}
          {{ form.username }}
        </div>
        <div class="mb-3">
          {{ form.password.label }}
          {{ form.password }}
        </div>
        <div class="form-group form-check">
          {{ form.remember_me() }}
          {{ form.remember_me.label(class_='form-check-label') }}
        </div>
        {{ form.submit() }}
      </form>
    </div>
    <div class="col-8">
    </div>
  </div>
{% endblock %}

web/webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="row">
    <div class='col-4'>
      <form action="{{ url_for('user.process_reg') }}" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3">
          {{ form.username.label }}
          {{ form.username }}
        </div>
        <div class="mb-3">
          {{ form.email.label }}
          {{ form.email }}
        </div>
        <div class="mb-3">
          {{ form.password.label }}
          {{ form.password }}
        </div>
        <div class="mb-3">
          {{ form.password2.label }}
          {{ form.password2 }}
        </div>
        {{ form.submit() }}
      </form>
    </div>
    <div class="col-8">
    </div>
  </div>
{% endblock %}